sudo: false
language: node_js
node_js: 7

cache: yarn
script: npm run test:travis

env:
  global:
    - CXX=g++-4.9

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy
  on:
    tags: false
    branch: master
    repo: jiangjianqing/atomer-common-lib
